### ISSUE TITLE
[RF06] - Gerenciar Categorias de Produtos

### ISSUE THREAD

**Issue by hdev14** [conab-devs/conab-frontend-web#5]
<p align="center">
:pencil: Desenvolver as telas e integrações relacionadas com o gerenciamento de categorias de produtos :pencil:
</p>

<img align="left" src="https://user-images.githubusercontent.com/44510574/90899362-2c8d0a00-e39e-11ea-8820-677e9e6090ea.png" width="350" />

<img src="https://user-images.githubusercontent.com/44510574/90899466-56dec780-e39e-11ea-9542-db9d5f621653.png" width="350" />

<img align="left" src="https://user-images.githubusercontent.com/44510574/90899589-8392df00-e39e-11ea-8a75-545d76366f87.png" width="350" />

<img src="https://user-images.githubusercontent.com/44510574/90899660-a1f8da80-e39e-11ea-9258-8144d734eb5e.png" width="350" />

<img src="https://user-images.githubusercontent.com/44510574/90899754-c785e400-e39e-11ea-80eb-04defce5c5a9.png" width="350" />

## Links úteis :pushpin:
>Adicione alguns links úteis, como documentos, imagens, vídeos, etc.

**Comment by FrankKleiton** [comment]
#26
